[package]
name = "advent2019"
version = "0.1.0"
authors = ["matejcik <ja@matejcik.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reduce = "*"
num = "*"
num-derive = "*"
num-traits = "*"
